import { Polygon, SeedConfiguration, Vector } from "$lib/classes";
import { TriangleType, QuadrilateralType, type TriangleSignature, type QuadrilateralSignature } from "./types";
// import { isWithinAngularTolerance, toDegrees } from "$utils";
// import { tolerance } from "$stores";

export class WallpaperGroup {
    name: string;
    sides: number;
    fundamentalDomainShapes: (TriangleType | QuadrilateralType)[];

    constructor(name: string, sides: number, fundamentalDomainShapes: (TriangleType | QuadrilateralType)[]) {
        this.name = name;
        this.sides = sides;
        this.fundamentalDomainShapes = fundamentalDomainShapes;
    }

    /**
     * @param seed the seed configuration
     * @param signature the signature of the fundamental domain
     * @returns true if the shape and symmetries match those of the wallpaper group
     */
    checkValidity = (seed: SeedConfiguration, signature: TriangleSignature | QuadrilateralSignature): boolean => {
        throw new Error('Abstract method called');
    }

    /**
     * @param processedSeed the processed seed configuration
     * @param cellStructure the cell structure
     * @param signature the signature of the fundamental domain
     * @returns true if the symmetries match those of the wallpaper group
     */
    checkSymmetries = (processedSeed: SeedConfiguration, cellStructure: Vector[], signature: TriangleSignature | QuadrilateralSignature): boolean => {
        throw new Error('Abstract method called');
    }

    /**
     * @param processedSeed the processed seed configuration
     * @param cellStructure the cell structure
     * @param signature the signature of the fundamental domain
     * @returns true if the mirror symmetries match those of the wallpaper group
     */
    checkMirrorSymmetries = (processedSeed: SeedConfiguration, cellStructure: Vector[], signature: TriangleSignature | QuadrilateralSignature): boolean => {
        throw new Error('Abstract method called');
    }

    /**
     * @param processedSeed the processed seed configuration
     * @param cellStructure the cell structure
     * @param signature the signature of the fundamental domain
     * @returns true if the rotational symmetries match those of the wallpaper group
     */
    checkRotationalSymmetries = (processedSeed: SeedConfiguration, cellStructure: Vector[], signature: TriangleSignature | QuadrilateralSignature): boolean => {
        throw new Error('Abstract method called');
    }

    /**
     * @param seed the seed configuration
     * @param signature the signature of the fundamental domain
     * @param layers the number of layers to apply
     * @returns the polygons generated by the wallpaper group
     */
    apply = (seed: SeedConfiguration, signature: TriangleSignature | QuadrilateralSignature, layers: number): Polygon[] => {
        throw new Error('Abstract method called');
    }

    /**
     * @param seed the seed configuration
     * @param signature the signature of the fundamental domain
     * @returns the processed seed configuration and the cell structure
     */
    buildCell = (seed: SeedConfiguration, signature: TriangleSignature | QuadrilateralSignature): [SeedConfiguration, Vector[]] => {
        throw new Error('Abstract method called');
    }

    encode = (): Object => {
        return {
            name: this.name,
            sides: this.sides,
            fundamentalDomainShapes: this.fundamentalDomainShapes,
        }
    }
}